namespace Estrutura.Shared.Enums
{
    public enum TipoOperacao
    {
        VENDA = 1,
        PEDIDO = 2,
        ORCAMENTO = 3,
        COMPRA = 4,
        DEVOLUCAO = 5,
        PEDIDO_COMPRA = 6,
        TRANSFERENCIA_PRODUTO_SAIDA = 7,
        TRANSFERENCIA_PRODUTO_ENTRADA = 8,
        DEVOLUCAO_COMPRA = 9,
        BRINDE = 10,
        PERDA = 11,
        AJUSTE_ESTOQUE_SAIDA = 12,
        AJUSTE_ESTOQUE_ENTRADA = 13,
        CONTAS_PAGAR = 14,
        CONTAS_RECEBER = 15,
        TRANSFERENCIA_DINHEIRO_SAIDA = 16,
        TRANSFERENCIA_DINHEIRO_ENTRADA = 17,
        TRANSFERENCIA_PRODUTO_RASCUNHO = 18,
        ENTRADA_MERCADORIA = 19,
        PAGAMENTO_COMPRA = 20,
        COMPRA_MERCADORIA = 21,
        CONFERENCIA_ESTOQUE_SAIDA = 22,
        CONFERENCIA_ESTOQUE_ENTRADA = 23
    }
}
